services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ZPI-frontend
    ports:
      - "5173:5173"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:3001
      - NODE_ENV=${development}
      - JWT_SECRET=${JWT_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
      - PORT=${PORT}

    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - internal

  postgres:
    image: postgres:16
    container_name: ZPI-postgres
    restart: always
    environment:
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ZPI-backend
    ports:
      - "3001:3001"
      - "51212:51212"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - FRONTEND_URL=${FRONTEND_URL}
      - JWT_SECRET=${JWT_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - PORT=${PORT}
    depends_on:
      - postgres
    networks:
      - internal

networks:
  internal:

volumes:
  postgres_data:
